# Generated by Django 6.0 on 2025-12-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('tipo_recurso', models.CharField(choices=[('libro', 'Libro'), ('paper', 'Paper Cientifico'), ('tesis', 'Tesis'), ('video', 'Video'), ('presentacion', 'Presentacion')], max_length=20)),
                ('archivo', models.FileField(upload_to='bibloteca/')),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publico', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
    ]
