# Generated by Django 6.0 on 2025-12-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app3', '0001_initial'),
        ('app9', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloEtiqueta',
            fields=[
                ('id_articuloetiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.articulo')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.etiqueta')),
            ],
        ),
    ]
