# Generated by Django 6.0 on 2025-12-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisor',
            fields=[
                ('id_revisor', models.AutoField(primary_key=True, serialize=False)),
                ('area_expertise', models.CharField(max_length=200)),
                ('max_articulos', models.IntegerField(default=5)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
    ]
