# Generated by Django 6.0 on 2025-12-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app3', '0001_initial'),
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id_revision', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completa', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('recomendacion', models.CharField(choices=[('aceptar', 'Aceptar'), ('aceptar_con_modificaciones', 'Aceptar con Modificaciones'), ('rechazar', 'Rechazar')], max_length=50)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.articulo')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.revisor')),
            ],
        ),
    ]
