# Generated by Django 6.0 on 2025-12-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='articulos',
            new_name='articulo',
        ),
    ]
